apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
<<<<<<< HEAD
  replicas: 7
=======
  replicas: 5
>>>>>>> 8ed0e5f05679798a33eb7c4160ce9b290413b043
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: xmaeltht/nginx
        name: nginx
